### ISSUE TITLE
Criar um define para cada prioridade

### ISSUE THREAD

**Issue by eduardomarossi** [BrunoSDomingues/APS_1-CompEmbarcada#5]
https://github.com/BrunoSDomingues/APS_1-CompEmbarcada/blob/93d972c900d098b0d54195d3a9643443693b50e3/src/main.c#L139-L146

Exemplo
```
// (Colocar este define junto com os outros do botão)
#define BUT2_PRIORITY 6

NVIC_SetPriority(BUT2_PIO_ID, BUT2_PRIORITY);
```

Vantagens:
- Fica explicito junto com as demais configurações do botão, permitindo fácil alteração da prioridade se necessário.
- Evita número "mágico" no meio do código, ficando bem óbvio o que se trata (código se auto documenta).

**Comment by BrunoSDomingues** [comment]
Defines feitos logo após o IDX_MASK de cada botão
