### ISSUE TITLE
Poderia ter uma função draw_music_title 

### ISSUE THREAD

**Issue by eduardomarossi** [BrunoSDomingues/APS_1-CompEmbarcada#6]
https://github.com/BrunoSDomingues/APS_1-CompEmbarcada/blob/93d972c900d098b0d54195d3a9643443693b50e3/src/main.c#L257-L258

Que tal?

```
void draw_music_title(char* status) {
    gfx_mono_draw_string(status, 50,16, &sysfont);
}
```

Vantagens:
- Separa lógica de processamento da lógica de exibição.
- Para alterar a interface visual no OLED, basta alterar uma função, ficando bem claro, o seu uso. Evitando ter código repetido espalhado.

**Comment by BrunoSDomingues** [comment]
Criada a função write_song_title para editar o título e a função clear_display que limpa o display antes de escrever o novo título.
